### ISSUE TITLE
latest on Docker Hub is not from experimental-branch, but from master

### ISSUE THREAD

**Issue by tanelikaivola** [Rfvgyhn/docker-factorio#2]
https://hub.docker.com/r/rfvgyhn/factorio/builds/bzwraulsk7ivzl9kmxfavuo/

This build is 0.15.40 instead of 0.16.11 which it should be.

(Maybe consider adding experimental tag in Docker Hub or some other way that could prevent latest from ever being anything else but experimental.)

**Comment by rfvgyhn** [comment]
Thanks for letting me know. I was mucking around with manual builds and apparently triggered one on the master branch. Should be fixed now.
